version: 2.1
jobs:
  build_library:
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: ./gradlew :library:assemble
      - store_artifacts:
          path: library/build/outputs/aar/library-release.aar
          destination: library-release.aar
  test_library:
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: ./gradlew library:testReleaseUnitTest
      - store_test_results:
          path: library/build/test-results/
  build_demo:
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: ./gradlew demo:assemble
      - store_artifacts:
          path: demo/build/outputs/apk/release/demo-release.apk
          destination: demo-release.apk
  test_demo:
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: ./gradlew demo:testReleaseUnitTest
      - store_test_results:
          path: demo/build/test-results/
  ensure_release_allowed:
    docker:
      - image: circleci/node:13.8
    steps:
      - checkout
      - run: ./.circleci/ensure_release_allowed.sh
  release_on_github:
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: ./gradlew library:assembleRelease
      - run: ./gradlew demo:assembleRelease
      - run: ./.circleci/release_github.sh
  release_on_central:
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Decript GPG secret keyring
          command: openssl aes-256-cbc -md sha512 -iter 100000 -d -in secring.gpg.enc -out secring.gpg -k $GPG_SECRET_DECRIPTION_KEY
          when: always
      - run:
          name: Upload library to Maven Central
          command: ./gradlew :annotations:publishReleasePublicationToSonatypeRepository --no-daemon --no-build-cache --refresh-dependencies
          when: always
      - run:
          name: Close and release staging repository in Nexus
          command: ./gradlew closeAndReleaseRepository
          when: always
  release_demo_on_google_play:
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: ./gradlew demo:assembleRelease
      - run: echo $(git describe --abbrev=0) > demo/src/main/play/release-names/alpha.txt
      - run: openssl aes-256-cbc -d -in api-release.json.enc -out api-release.json -k "$ENCRYPTION_KEY"
      - run: ./gradlew demo:publishReleaseBundle
workflows:
  version: 2.1
  test:
    jobs:
      - build_library
      - test_library:
          requires:
            - build_library
      - build_demo
      - test_demo:
          requires:
            - build_demo
  release:
    jobs:
      - build_library:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - test_library:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
          requires:
            - build_library
      - build_demo:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - test_demo:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
          requires:
            - build_demo
      - ensure_release_allowed:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - release_on_central:
          context: test-accessors_release_mavencentral
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
          requires:
            - ensure_release_allowed
            - test_library
      - release_on_github:
          context: otpview_release_github
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
          requires:
            - ensure_release_allowed
            - test_library
            - test_demo
      - release_demo_on_google_play:
          context: otpview_release_google_play
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
          requires:
            - ensure_release_allowed
            - test_demo
